import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Server,RefreshCw,Plus,ShieldCheck,Activity,Trash2,Layers,CheckCircle2,Play,Settings}from'lucide-react';import'./style.css';
const API='/api';
function App(){const[servers,setServers]=useState([]),[jobs,setJobs]=useState([]),[baselines,setBaselines]=useState([]),[selected,setSelected]=useState([]),[comp,setComp]=useState({}),[tab,setTab]=useState('servers'),[form,setForm]=useState({name:'',address:'',username:'root',password:''}),[base,setBase]=useState({model:'PowerEdge R750',component:'BIOS',target_version:'',image_uri:''});
const load=()=>Promise.all([fetch(API+'/servers').then(r=>r.json()),fetch(API+'/jobs').then(r=>r.json()),fetch(API+'/baselines').then(r=>r.json())]).then(([s,j,b])=>{setServers(s);setJobs(j);setBaselines(b)});useEffect(()=>{load()},[]);
const post=(u,b)=>fetch(API+u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}).then(async r=>{if(!r.ok)throw new Error((await r.json()).detail||r.statusText);return r.json()});
const add=async e=>{e.preventDefault();await post('/servers',form);setForm({name:'',address:'',username:'root',password:''});load()};
const scan=async id=>{await post(`/servers/${id}/scan`,{});load()};const compliance=async id=>{const x=await post(`/servers/${id}/compliance`,{});setComp({...comp,[id]:x})};
const del=async id=>{if(confirm('Remove server?')){await fetch(`${API}/servers/${id}`,{method:'DELETE'});load()}};const addBase=async e=>{e.preventDefault();await post('/baselines',base);setBase({...base,target_version:'',image_uri:''});load()};
const group=async()=>{let n=prompt('Group name for selected servers:','Production');if(n)await post('/groups',{server_ids:selected,group_name:n});load()};
const rolling=async()=>{if(!selected.length)return alert('Select one or more servers first.');let c=prompt('Firmware component to update:','BIOS');if(!c)return;try{let r=await post('/rolling-update',{server_ids:selected,component:c,stop_on_failure:true});alert(`Batch ${r.batch_id} submitted. ${r.results.length} server(s) processed.`);load()}catch(e){alert(e.message)}};
return <><header><div className="brand"><ShieldCheck/> Dell FleetOps <em>v0.2</em></div><span>Centralized iDRAC Lifecycle Management</span></header><main><section className="stats"><Card t="Managed Servers" v={servers.length}/><Card t="Healthy" v={servers.filter(x=>x.health==='OK').length}/><Card t="Approved Baselines" v={baselines.filter(x=>x.approved).length}/><Card t="Update Jobs" v={jobs.length}/></section><nav><button onClick={()=>setTab('servers')} className={tab==='servers'?'active':''}><Server size={16}/>Fleet</button><button onClick={()=>setTab('baseline')} className={tab==='baseline'?'active':''}><Layers size={16}/>Baselines</button><button onClick={()=>setTab('jobs')} className={tab==='jobs'?'active':''}><Activity size={16}/>Jobs</button></nav>
{tab==='servers'&&<><section className="panel"><div className="panelhead"><h2><Server/> Server Inventory</h2><div><button className="secondary" onClick={group}><Settings size={15}/>Assign Group</button><button onClick={rolling}><Play size={15}/>Rolling Update</button></div></div><form onSubmit={add}><input required placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="iDRAC IP / DNS" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><input required placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input required type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button><Plus size={16}/>Add</button></form><table><thead><tr><th></th><th>Name</th><th>Group</th><th>iDRAC</th><th>Model</th><th>Service Tag</th><th>BIOS</th><th>iDRAC FW</th><th>Health</th><th>Actions</th></tr></thead><tbody>{servers.map(s=><React.Fragment key={s.id}><tr><td><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(x=>x!==s.id))}/></td><td>{s.name}</td><td><span className="tag">{s.group_name||'Default'}</span></td><td>{s.address}</td><td>{s.model}</td><td>{s.service_tag}</td><td>{s.bios_version}</td><td>{s.idrac_version}</td><td><span className={'pill '+(s.health==='OK'?'ok':'')}>{s.health}</span></td><td><button title="Inventory scan" className="icon" onClick={()=>scan(s.id)}><RefreshCw size={16}/></button><button title="Compliance scan" className="icon good" onClick={()=>compliance(s.id)}><CheckCircle2 size={16}/></button><button className="icon danger" onClick={()=>del(s.id)}><Trash2 size={16}/></button></td></tr>{comp[s.id]&&<tr className="detail"><td></td><td colSpan="9"><b>Firmware compliance:</b> {comp[s.id].map((x,i)=><span key={i} className={'compliance '+(x.status==='Compliant'?'pass':x.status==='Update Available'?'warn':'')}>{x.name}: {x.version} → {x.target||'No baseline'} ({x.status})</span>)}</td></tr>}</React.Fragment>)}</tbody></table></section></>}
{tab==='baseline'&&<section className="panel"><h2><Layers/> Approved Firmware Baselines</h2><p className="muted">Define a tested target version and firmware URI per PowerEdge model/component. FleetOps will never infer an update URI from version numbers.</p><form onSubmit={addBase}><input required placeholder="Model" value={base.model} onChange={e=>setBase({...base,model:e.target.value})}/><input required placeholder="Component" value={base.component} onChange={e=>setBase({...base,component:e.target.value})}/><input required placeholder="Target version" value={base.target_version} onChange={e=>setBase({...base,target_version:e.target.value})}/><input required placeholder="HTTPS firmware URI" value={base.image_uri} onChange={e=>setBase({...base,image_uri:e.target.value})}/><button><Plus size={16}/>Approve</button></form><table><thead><tr><th>Model</th><th>Component</th><th>Target</th><th>Firmware URI</th><th>Approved</th></tr></thead><tbody>{baselines.map(b=><tr key={b.id}><td>{b.model}</td><td>{b.component}</td><td>{b.target_version}</td><td className="uri">{b.image_uri}</td><td>{b.approved?'Yes':'No'}</td></tr>)}</tbody></table></section>}
{tab==='jobs'&&<section className="panel"><h2><Activity/> Job History</h2>{jobs.length?jobs.map(j=><div className="job" key={j.id}><span>#{j.id} {j.batch_id&&`[${j.batch_id}]`} Server {j.server_id} — {j.action}</span><b className={j.status==='Completed'?'success':''}>{j.status}</b></div>):<p>No jobs yet.</p>}</section>}</main></>}
function Card(p){return <div className="card"><small>{p.t}</small><strong>{p.v}</strong></div>}createRoot(document.getElementById('root')).render(<App/>);